import React from 'react';
import { Link } from 'react-router-dom';

const TermsPage = () => {
  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4">
      <div className="max-w-3xl mx-auto bg-white rounded-2xl shadow-sm p-8 sm:p-12">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
        <p className="text-gray-400 text-sm mb-8">Effective date: January 2025</p>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-800 mb-3">1. Acceptance of Terms</h2>
          <p className="text-gray-600 leading-relaxed">
            By creating an account and using PadaiSathi, you agree to these Terms of Service. If you do not agree, please do not use the platform.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-800 mb-3">2. Use of the Platform</h2>
          <p className="text-gray-600 leading-relaxed">
            PadaiSathi is an AI-powered study platform designed for students. You agree to use it only for lawful, educational purposes. You must not misuse the platform, attempt to gain unauthorized access, or upload content that is harmful, offensive, or violates intellectual property rights.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-800 mb-3">3. User Accounts</h2>
          <p className="text-gray-600 leading-relaxed">
            You are responsible for maintaining the security of your account and password. PadaiSathi is not liable for any loss or damage resulting from unauthorized access to your account.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-800 mb-3">4. AI-Generated Content</h2>
          <p className="text-gray-600 leading-relaxed">
            Summaries, flashcards, quizzes, and videos generated by PadaiSathi are powered by AI and are intended as study aids only. We do not guarantee the accuracy of AI-generated content. Always cross-reference with your official course materials.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-800 mb-3">5. Uploaded Documents</h2>
          <p className="text-gray-600 leading-relaxed">
            By uploading documents to PadaiSathi, you confirm that you have the right to share that content. Your uploaded files are used solely to generate study materials for your personal use.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-800 mb-3">6. Changes to Terms</h2>
          <p className="text-gray-600 leading-relaxed">
            We may update these terms from time to time. Continued use of the platform after changes constitutes acceptance of the new terms.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-800 mb-3">7. Contact</h2>
          <p className="text-gray-600 leading-relaxed">
            If you have any questions about these terms, please contact us at <span className="text-blue-500">shresthajeshmin30@gmail.com</span>.
          </p>
        </section>

        <Link to="/register" className="text-blue-500 hover:underline text-sm">
          ← Back to Register
        </Link>
      </div>
    </div>
  );
};

export default TermsPage;
